name: CI - Product Analytics Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python files
        run: |
          pip install pylint
          pylint scripts/**/*.py \
          dashboard/*.py \
          dashboard/utils/*.py \
          dashboard/pages/*.py \
          airflow/dags/*.py || true

